version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-actions:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/extractors/cds/tools"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/cap/test/models/cds/entityreference"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/cap/test/models/cds/remoteflowsources"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/cap/test/queries/bad-authn-authz/entities-with-no-authz/entities-exposed-with-cds-authz"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/cap/test/queries/bad-authn-authz/entities-with-no-authz/entities-exposed-with-js-authz"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/cap/test/queries/bad-authn-authz/entities-with-no-authz/entities-exposed-with-js-authz-cds-serve"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/cap/test/queries/bad-authn-authz/entities-with-no-authz/entities-exposed-with-no-authz"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/cap/test/queries/bad-authn-authz/misused-privileged-user/default-is-privileged"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/cap/test/queries/bad-authn-authz/misused-privileged-user/unnecessarily-granted-privileged-access-rights"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/cap/test/queries/bad-authn-authz/nonprod-authn-strategy/basic-authentication"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/cap/test/queries/bad-authn-authz/nonprod-authn-strategy/dummy-authentication"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/cap/test/queries/bad-authn-authz/nonprod-authn-strategy/mocked-authentication"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/cap/test/queries/cqlinjection"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/cap/test/queries/loginjection/log-injection-not-depending-on-request"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/cap/test/queries/loginjection/log-injection-type-sanitized"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/cap/test/queries/loginjection/log-injection-with-complete-protocol-none"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/cap/test/queries/loginjection/log-injection-with-service1-protocol-none"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/cap/test/queries/loginjection/log-injection-with-service2-protocol-none"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/cap/test/queries/loginjection/log-injection-without-protocol-none"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5-webcomponents/test/queries/xss-input-dangerouslySetInnerHTML"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/models/dynamic_write_to_html_content"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/models/external_model_manifest"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/models/multiple_models"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5FormulaInjection/formula-custom-control-property-sanitized"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5FormulaInjection/formula-custom-control-sanitized"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5FormulaInjection/formula-html-control-df"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5LogInjection/log-custom-control-property-sanitized"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5LogInjection/log-custom-control-sanitized"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5LogInjection/log-entry-flows-to-http-getLogEntries"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5LogInjection/log-entry-flows-to-http-log-listener-js-object"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5LogInjection/log-entry-flows-to-http-log-listener-sap-module"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5LogInjection/log-entry-flows-to-http-log-listener-sap-module-imported"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5LogInjection/log-entry-flows-to-notifications"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5LogInjection/log-entry-flows-to-sinks"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5LogInjection/log-html-control-df"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5PathInjection/path-custom-control-property-sanitized"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5PathInjection/path-custom-control-sanitized"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5PathInjection/path-html-control-df"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5Xss/xss-book-example"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5Xss/xss-cross-app-isolation"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5Xss/xss-custom-control-api1"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5Xss/xss-custom-control-apis/xss-custom-control-api3"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5Xss/xss-custom-control-apis/xss-custom-control.api2"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5Xss/xss-custom-control-jquery"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5Xss/xss-custom-control-property-sanitized"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5Xss/xss-custom-control-sanitized"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5Xss/xss-event-handlers"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5Xss/xss-eventbus-with-data"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5Xss/xss-fragment-odata-default-model"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5Xss/xss-fragment-static-byid"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5Xss/xss-html-control"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5Xss/xss-html-control-df"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5Xss/xss-html-control-oneway"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5Xss/xss-html-control-sanitized"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5Xss/xss-html-external-model"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5Xss/xss-html-view"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5Xss/xss-indirect-control"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5Xss/xss-js-view"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5Xss/xss-json-view"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5Xss/xss-separate-renderer"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5Xss/xss-separate-renderer-byname"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5Xss/xss-urlparams-jsonmodel"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5Xss/xss-webc-control"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5Xss/xss-xml-fragment"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
  - package-ecosystem: "npm"
    directory: "/javascript/frameworks/ui5/test/queries/UI5Xss/xss-xml-fragment-load"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7
