name: "Code Scanning"

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '39 12 * * 2'
    
env:
  LGTM_INDEX_XML_MODE: all

jobs:
  analyze:
    name: Analyze
    runs-on: 'ubuntu-latest'
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Prepare local CodeQL model packs
      run: |
        mkdir -p .github/codeql/extensions
        for ext in $(find . -name 'qlpack.yml' -exec fgrep -l dataExtensions {} \;); do
          dir=$(dirname $ext)
          echo "Moving $ext to .github/codeql/extensions/$dir"
          mkdir -p .github/codeql/extensions/$dir
          mv $dir .github/codeql/extensions/$dir
        done

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: javascript
        config-file: ./.github/codeql/codeql-config.yaml
        debug: true

    - name: Perform CodeQL Analysis
      id: analyze
      uses: github/codeql-action/analyze@v3
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
        cache: 'pip'
        
    - name: Validate results
      continue-on-error: true
      id: validate
      run: |
        pip install sarif-tools
        sarif --version
        sarif diff ${{ steps.analyze.outputs.sarif-output }} .github/workflows/javascript.sarif.expected -o sarif-diff.json
        ! grep -q "[1-9]" sarif-diff.json
        
    - name: Upload sarif-diff
      if: steps.validate.outcome != 'success'
      uses: actions/upload-artifact@v4
      with:
        name: sarif-diff.json
        path: |
          sarif-diff.json
          ${{ steps.analyze.outputs.sarif-output }}
    
    - name: Unexpected Code Scanning results
      if: steps.validate.outcome != 'success'
      run: |
        cat sarif-diff.json
        echo "::error::Unexpected Code Scanning results!" && exit 1
      
