name: "Code Scanning"

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '39 12 * * 2'
    
env:
  LGTM_INDEX_XML_MODE: all
  CODEQL_ACTION_EXTRA_OPTIONS: '{"database": {"run-queries": ["--additional-packs=${{ github.workspace }}/javascript/frameworks/ui5/lib"]}}'

jobs:
  analyze:
    name: Analyze
    runs-on: 'ubuntu-latest'
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL to discover CodeQL path
      id: resolve-codeql-path
      uses: github/codeql-action/init@v2
      with:
        languages: javascript
        db-location: ${{ runner.temp }}/temp-db

    - name: Resolve local pack dependencies
      env:
        CODEQL_PATH: ${{ steps.resolve-codeql-path.outputs.codeql-path }}
      run: |
        find . -name 'qlpack.yml' -exec $CODEQL_PATH pack install {} \;

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: javascript
        config-file: ./.github/codeql/codeql-config.yaml
        debug: true

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
