name: "Code Scanning"

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '39 12 * * 2'
    
env:
  LGTM_INDEX_XML_MODE: all

jobs:
  analyze:
    name: Analyze
    runs-on: 'ubuntu-latest'
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Prepare local CodeQL model packs
      run: |
        mkdir -p .github/codeql/extensions
        for ext in $(find . -name 'qlpack.yml' -exec fgrep -l dataExtensions {} \;); do
          dir=$(dirname $ext)
          echo "Moving $ext to .github/codeql/extensions/$dir"
          mkdir -p .github/codeql/extensions/$dir
          mv $dir .github/codeql/extensions/$dir
        done


    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: javascript
        config-file: ./.github/codeql/codeql-config.yaml
        debug: true

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
